insert into model_manufacturer (model, manufacturer) values ('Navigator', 'Lincoln');
insert into model_manufacturer (model, manufacturer) values ('350Z', 'Nissan');
insert into model_manufacturer (model, manufacturer) values ('Thunderbird', 'Ford');
insert into model_manufacturer (model, manufacturer) values ('Bravada', 'Oldsmobile');
insert into model_manufacturer (model, manufacturer) values ('IS', 'Lexus');
insert into model_manufacturer (model, manufacturer) values ('CC', 'Volkswagen');
insert into model_manufacturer (model, manufacturer) values ('DeVille', 'Cadillac');
insert into model_manufacturer (model, manufacturer) values ('Golf', 'Volkswagen');
insert into model_manufacturer (model, manufacturer) values ('LX', 'Lexus');
insert into model_manufacturer (model, manufacturer) values ('Quattroporte', 'Maserati');
insert into model_manufacturer (model, manufacturer) values ('SJ', 'Suzuki');
insert into model_manufacturer (model, manufacturer) values ('Prowler', 'Plymouth');
insert into model_manufacturer (model, manufacturer) values ('Bonneville', 'Pontiac');
insert into model_manufacturer (model, manufacturer) values ('Tiburon', 'Hyundai');
insert into model_manufacturer (model, manufacturer) values ('Ram Wagon B250', 'Dodge');
insert into model_manufacturer (model, manufacturer) values ('M-Class', 'Mercedes-Benz');
insert into model_manufacturer (model, manufacturer) values ('V70', 'Volvo');
insert into model_manufacturer (model, manufacturer) values ('Avalanche 2500', 'Chevrolet');
insert into model_manufacturer (model, manufacturer) values ('Coupe GT', 'Audi');
insert into model_manufacturer (model, manufacturer) values ('Corvette', 'Chevrolet');
insert into model_manufacturer (model, manufacturer) values ('MDX', 'Acura');
insert into model_manufacturer (model, manufacturer) values ('Corvette', 'Chevrolet');
insert into model_manufacturer (model, manufacturer) values ('Savana 3500', 'GMC');
insert into model_manufacturer (model, manufacturer) values ('Excursion', 'Ford');
insert into model_manufacturer (model, manufacturer) values ('STS', 'Cadillac');
insert into model_manufacturer (model, manufacturer) values ('4Runner', 'Toyota');
insert into model_manufacturer (model, manufacturer) values ('Fiero', 'Pontiac');
insert into model_manufacturer (model, manufacturer) values ('Taurus', 'Ford');
insert into model_manufacturer (model, manufacturer) values ('Dakota', 'Dodge');
insert into model_manufacturer (model, manufacturer) values ('Jetta', 'Volkswagen');
insert into model_manufacturer (model, manufacturer) values ('Venture', 'Chevrolet');
insert into model_manufacturer (model, manufacturer) values ('F150', 'Ford');
insert into model_manufacturer (model, manufacturer) values ('E-Class', 'Mercedes-Benz');
insert into model_manufacturer (model, manufacturer) values ('Azera', 'Hyundai');
insert into model_manufacturer (model, manufacturer) values ('Miata MX-5', 'Mazda');
insert into model_manufacturer (model, manufacturer) values ('Intrepid', 'Dodge');
insert into model_manufacturer (model, manufacturer) values ('Regal', 'Buick');
insert into model_manufacturer (model, manufacturer) values ('Tempo', 'Ford');
insert into model_manufacturer (model, manufacturer) values ('Sentra', 'Nissan');
insert into model_manufacturer (model, manufacturer) values ('Suburban 2500', 'GMC');
insert into model_manufacturer (model, manufacturer) values ('Sable', 'Mercury');
insert into model_manufacturer (model, manufacturer) values ('Voyager', 'Plymouth');
insert into model_manufacturer (model, manufacturer) values ('LeMans', 'Pontiac');
insert into model_manufacturer (model, manufacturer) values ('5 Series', 'BMW');
insert into model_manufacturer (model, manufacturer) values ('5000S', 'Audi');
insert into model_manufacturer (model, manufacturer) values ('Cobalt', 'Chevrolet');
insert into model_manufacturer (model, manufacturer) values ('W201', 'Mercedes-Benz');
insert into model_manufacturer (model, manufacturer) values ('CL', 'Acura');
insert into model_manufacturer (model, manufacturer) values ('Murano', 'Nissan');
insert into model_manufacturer (model, manufacturer) values ('9-3', 'Saab');
insert into model_manufacturer (model, manufacturer) values ('Estate', 'Buick');
insert into model_manufacturer (model, manufacturer) values ('Land Cruiser', 'Toyota');
insert into model_manufacturer (model, manufacturer) values ('Colt', 'Dodge');
insert into model_manufacturer (model, manufacturer) values ('Ram Van B350', 'Dodge');
insert into model_manufacturer (model, manufacturer) values ('PT Cruiser', 'Chrysler');
insert into model_manufacturer (model, manufacturer) values ('Escape', 'Ford');
insert into model_manufacturer (model, manufacturer) values ('190E', 'Mercedes-Benz');
insert into model_manufacturer (model, manufacturer) values ('Regal', 'Buick');
insert into model_manufacturer (model, manufacturer) values ('GTI', 'Volkswagen');
insert into model_manufacturer (model, manufacturer) values ('Grand Prix', 'Pontiac');
insert into model_manufacturer (model, manufacturer) values ('S10', 'Chevrolet');
insert into model_manufacturer (model, manufacturer) values ('Suburban 1500', 'Chevrolet');
insert into model_manufacturer (model, manufacturer) values ('XF', 'Jaguar');
insert into model_manufacturer (model, manufacturer) values ('Grand Marquis', 'Mercury');
insert into model_manufacturer (model, manufacturer) values ('Camry', 'Toyota');
insert into model_manufacturer (model, manufacturer) values ('Navigator', 'Lincoln');
insert into model_manufacturer (model, manufacturer) values ('Biturbo', 'Maserati');
insert into model_manufacturer (model, manufacturer) values ('Montego', 'Mercury');
insert into model_manufacturer (model, manufacturer) values ('Grand Am', 'Pontiac');
insert into model_manufacturer (model, manufacturer) values ('Windstar', 'Ford');
insert into model_manufacturer (model, manufacturer) values ('Biturbo', 'Maserati');
insert into model_manufacturer (model, manufacturer) values ('Journey', 'Dodge');
insert into model_manufacturer (model, manufacturer) values ('9000', 'Saab');
insert into model_manufacturer (model, manufacturer) values ('928', 'Porsche');
insert into model_manufacturer (model, manufacturer) values ('Eos', 'Volkswagen');